name: Deploy application
on:
  push:
    branches: 
      - main

jobs:
  run_build_job:
    name: Deploy application Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to project
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
        
      - name: Installing dependencies
        run: npm ci

      - name: Building
        run: npm run build
